ALTER TABLE public.tasks
ADD COLUMN IF NOT EXISTS lead_id UUID REFERENCES public.leads(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS deal_id UUID REFERENCES public.deals(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'normal';
